# Generated by Django 4.0.2 on 2022-03-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='contract_abi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='contract_byte_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
