# Generated by Django 4.0.2 on 2022-05-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eth', '0002_station_contract_abi_station_contract_byte_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
